SRCS= \
	main.c \
	handlers.c \
	print_error.c \
	execute_inbuilt_command.c \
	cmds.c \
	export_cmd.c \
	env_utils.c \
	env_utils2.c \
	env_utils3.c \
	term_handlers.c \
	search_exec.c \
	line_tokenizer.c \
	utils.c \
	utils2.c \
	line_tokenizer_utils.c\
	lexical_analysis.c \
	checks.c \
	checks2.c \
	checks3.c \
	checks4.c \
	checks5.c \
	checks6.c \
	validate.c \
	expander.c \
	expander_utils.c \
	expander_utils2.c \
	expander_pre_wildcards.c \
	expander_pre_wildcards_utils.c \
	expander_wildcard.c \
	expander_wildcard_utils.c \
	handlers2.c \
	check_pairs.c \
	operations_prep.c \
	operations_prep_utils.c \
	operations_prep_utils2.c \
	operations_prep_utils3.c \
	execute_process.c