SRCS= \
	main.c \
	handlers.c \
	handlers2.c \
	print_error.c \
	execute_inbuilt_command.c \
	cmds.c \
	cmds2.c \
	export_cmd.c \
	env_utils.c \
	env_utils2.c \
	env_utils3.c \
	env_utils4.c \
	term_handlers.c \
	search_exec.c \
	line_tokenizer.c \
	utils.c \
	utils2.c \
	utils3.c \
	line_tokenizer_utils.c \
	lexical_analysis.c \
	checks.c \
	checks2.c \
	checks3.c \
	checks4.c \
	checks5.c \
	checks6.c \
	validate.c \
	expander.c \
	expander_qtr.c \
	expander_remove_quotes.c \
	expander_utils.c \
	expander_utils2.c \
	expander_utils3.c \
	expander_wildcard.c \
	expander_wildcard_utils.c \
	expander_split.c \
	execute_expander.c \
	operations_prep.c \
	operations_prep_utils.c \
	operations_prep_utils2.c \
	operations_prep_utils3.c \
	execute_process.c \
	execute_builtin.c\
	exit_cmd.c